//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RAIN.Core;
using RAIN.Serialization;

[RAINSerializableClass, RAINElement("Radio")]
public class RadioElement : CustomAIElement
{
	[RAINSerializableField(Visibility = FieldVisibility.Show, ToolTip = "")]
	private string sender = "";

	public override void AIInit()
	{
		base.AIInit();
		ListenTo ();	
	}

	public void ListenTo() {
		RadioManager.Singleton.Listen (this);
	}

	public void ReceiveMessage(string sender, string variableName, object value) {
		if (!this.sender.Equals (sender)) {
			AI.WorkingMemory.SetItem<object> (variableName, value);
		}
	}

	public void RadioMessage(string sender, string variableName, object value) {
		RadioManager.Singleton.RadioMessage (sender, variableName, value);
	}
}


